### ISSUE TITLE
Enlace a recomendaciones de publicación de agendas

### ISSUE THREAD

**Issue by dcabo** [civio/civio-propuestas#1]
Deberíamos añadir un enlace a nuestras [recomendaciones sobre publicación de agendas](https://civio.app.box.com/s/z578ox9psa5hxxzte1ignadoso2zc1qn). O mejor aún, a una copia, que los enlaces a Box no son muy estables.

**Comment by EvaBelmonte** [comment]
Agree

**Comment by dcabo** [comment]
Cierro esto porque esta web de propuestas no es la actual, y desaparecerá en cuanto podamos hacer limpieza.
